---
- name: Creamos el directorio de configuración /etc/rancher/rke2
  file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: Agregamos archivo de configuración de audit policy
  copy:
    src: "{{ audit_policy_config_file_path }}"
    dest: "/etc/rancher/rke2/audit-policy.yaml"
    mode: '0640'
    owner: root
    group: root
