---
- name: "Buscamos imagenes tar.gz en {{ playbook_dir }}/tarball_install/rke2-images.linux-amd64.tar.gz"  # noqa name[template] yaml[line-length]
  stat:
    path: "{{ playbook_dir }}/tarball_install/rke2-images.linux-amd64.tar.gz"
    get_checksum: false
  register: got_images_gz
  delegate_to: 127.0.0.1
  become: false

- name: "Buscamos imagenes tar.zst en {{ playbook_dir }}/tarball_install/rke2-images.linux-amd64.tar.zst"  # noqa name[template] yaml[line-length]
  stat:
    path: "{{ playbook_dir }}/tarball_install/rke2-images.linux-amd64.tar.zst"
    get_checksum: false
  register: got_images_zst
  delegate_to: 127.0.0.1
  become: false

- name: Agregamos imagenes tar.gz al directorio necesario
  copy:
    src: "{{ playbook_dir }}/tarball_install/rke2-images.linux-amd64.tar.gz"
    dest: /var/lib/rancher/rke2/agent/images/
    mode: '0644'
  when: got_images_gz.stat.exists

- name: Agregamos imagenes tar.zst al directorio necesario
  copy:
    src: "{{ playbook_dir }}/tarball_install/rke2-images.linux-amd64.tar.zst"
    dest: /var/lib/rancher/rke2/agent/images/
    mode: '0644'
  when: got_images_zst.stat.exists
