---

- name: Comprobamos si estaba ya instalado previamente el rke2-server
  ansible.builtin.debug:
    msg: "rke2-server is already installed. Skipping installation steps."
  when: >
    ansible_facts.services["rke2-server.service"] is defined
    and not ansible_facts.services["rke2-server.service"].status == 'disabled'

- name: Establecemos rke2-server estaba instalado previamente
  set_fact:
    installed: true
  when: >
    ansible_facts.services["rke2-server.service"] is defined
    and not ansible_facts.services["rke2-server.service"].status == 'disabled'

- name: Comprobamos si estaba ya instalado previamente el rke2-agent
  ansible.builtin.debug:
    msg: "rke2-agent is already installed. Skipping installation steps."
  when: >
    ansible_facts.services["rke2-agent.service"] is defined
    and not ansible_facts.services["rke2-agent.service"].status == 'disabled'

- name: Establecemos rke2-agent estaba instalado previamente
  set_fact:
    installed: true
  when: >
    ansible_facts.services["rke2-agent.service"] is defined
    and not ansible_facts.services["rke2-agent.service"].status == 'disabled'
