apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wikijs
type: Opaque
data:
  ROOT: cm9vdA==
  ROOT_PASSWORD: U3Ryb25nUm9vdFBhc3N3b3Jk
  DATABASE: d2lraWpz
  USER: d2lraWpz
  PASSWORD: V2lraWpzVXNlclBhc3N3MHJk
