---
# ansible
ansible_user: root
ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
registry_user: "{{ vault_registry_user }}"
registry_pass: "{{ vault_registry_pass }}"

# entorno : cambiar para instalar cada cluster
entorno: pr

# comun para todas las maquinas
user_name: xpkami01
user_group: gpkami01
user_home_dir: kamino
selinux_state: permissive

# hostnames
hostname_master: master
hostname_worker1: worker1
hostname_worker2: worker2
hostname_registry: registry
hostname_loadbalancer1: loadbalancer1
hostname_loadbalancer2: loadbalancer2
# hostname_vipa: vipa
# hostname_bastion: bastion


# IP's
ip_master: 192.168.112.183
ip_worker1: 192.168.112.184
ip_worker2: 192.168.112.185
ip_registry: 192.168.112.186
ip_loadbalancer1: 192.168.112.187
ip_loadbalancer2: 192.168.112.188
# ip_vipa: 192.168.112.189
# ip_bastion: 192.168.112.190

# Proxy Docker Hub
proxy_docker_hub: proxy_docker_hub

# Registry domain
registry_domain: registry
registry_hostname: registry
registry_ip: 192.168.112.186

# Registry Port
registry_port: 443

# Registry admin password
harbor_admin_password: cylonb0x

# Proxy
proxy: "http://10.200.140.230:80"

# Image versions
image_pause_version: "3.6"
etcd_image_version: "3.5.1-0"

# Kubernetes version
kubernetes_version: 1.23.6

# POD CIDR
pod_network_cidr: 10.20.0.0/16

