---
- name: Trident
  block:
    ## Necesario kubectl instalado y configurado previamente
    ## Pendiente de pasar ficheros de config de Trident
    - name: Extraemos el contenido del fichero de tridentctl
      unarchive:
        src: "files/trident-installer-22.04.0.tar.gz"
        dest: "/tmp"
        owner: root
        group: root
        mode: '0744'

    - name: Movemos el binario de tridentctl a /usr/local/bin/
      copy:
        src: "/tmp/trident-installer/tridentctl"
        dest: "/usr/local/bin/tridentctl"
        owner: root
        group: root
        mode: '0755'
        remote_src: yes

    # Pendiente de completar
    - name: Instalación de binario de tridenctl
      command: tridentctl install -n trident --use-custom-yaml /tmp/trident-installer/config-netapp.yaml --image-registry {{ ip_registry }}:{{ registry_port }} --k8s-timeout 5m
      become: yes
      become_user: root

    - name: Create backend
      shell: /tmp/trident-installer/tridentctl -n trident create backend -f /tmp/trident-installer/backend-ontap-nas.json
      become: yes
    
    - name: Create storage class
      shell: kubectl create -f /tmp/trident-installer/storage-class-ontapnas.yaml
      become: yes

    - name: Borramos los ficheros generados en /tmp/trident-installer/
      file:
        state: absent
        path: /tmp/trident-installer/

  when: inventory_hostname == groups['masters'][0]
  tags: trident
