---
# handler for haproxy
- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
  become: yes

# handler for keepalived
- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
  become: yes

