---

- name: Agregamos archivos de manifiesto
  include_role:
    name: rke2_common
    tasks_from: add-manifest-addons.yml
  when:
    - manifest_config_file_path is defined
    - manifest_config_file_path | length > 0

- name: Iniaciamos rke2-server
  systemd:
    name: rke2-server
    state: started
    enabled: yes

- name: Esperamos al k8s apiserver
  wait_for:
    host: "{{ kubernetes_api_server_host }}"
    port: "6443"
    state: present
    timeout: 300

- name: Esperamos a que el proceso de kubelet este presente en el host
  command: >-
    ps -C kubelet -F -ww --no-headers
  register: kubelet_check
  until: kubelet_check.rc == 0
  retries: 20
  delay: 10
  changed_when: false

- name: Extraemos el hostname-override del hostname del proceso kubelet  # noqa var-spacing
  set_fact:
    kubelet_hostname_override_parameter: "{{ kubelet_check.stdout |\
      regex_search('\\s--hostname-override=((([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9]))\\s',\
      '\\1') }}"

- name: Esperamos a que el nodo muestre el estado de listo
  command: >-
    /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml
    --server https://127.0.0.1:6443 get no {{ kubelet_hostname_override_parameter[0] }}
    -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
  register: status_result
  until: status_result.stdout.find("True") != -1
  retries: 20
  delay: 10
  changed_when: false

- name: Agregamos el token generado si no se proporciona ninguno
  block:
    - name: Wait for node-token
      wait_for:
        path: /var/lib/rancher/rke2/server/node-token

    - name: Leemos el node-token del master (rke2-server)
      slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: node_token

    - name: Guardamos el Master node-token
      set_fact:
        rke2_config_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
