---

- name: Creamos directorio /tmp/keepalived/ si no existe
  file:
    path: "/tmp/keepalived/"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    state: directory

- name: Movemos los paquetes de keepalived a /tmp/keepalived/ para instalar
  copy:
    src: "files/keepalived/{{ item }}"
    dest: "/tmp/keepalived/{{ item }}"
    owner: root
    group: root
    mode: '0744'
  with_items: "{{ keepalived }}"

- name: Instalamos keepalived con los paquetes en /tmp/keepalived/
  yum:
    name: "/tmp/keepalived/{{ item }}"
    state: present
    disablerepo: "*"
  with_items: "{{ keepalived }}"

- name: Habilitamos el servicio de Keepalived
  become: yes
  systemd:
    name: keepalived
    enabled: yes
    masked: no
 

- name: Copiamos la configuración de keepalived
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
  become: yes


- name: Removemos los paquetes de keepalived ya instalados de /tmp/keepalived/
  file:
    path: "/tmp/keepalived/"
    state: absent
