---
# tasks file for kubernetes

- name: Instalar Keepalived
  import_tasks: install-keepalived.yaml
  tags: keepalived-packet

- name: Instalar Haproxy
  import_tasks: install-haproxy.yaml
  tags: haproxy-packet
