---
#Pendiente eliminar quiza
- name: Ensure chrony package is installed
  ansible.builtin.package:
    name: chrony
    state: present
    
#Pendiente eliminar quiza
- name: Enable and start chronyd service
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes
- name: Synchronize time manually
  ansible.builtin.shell:  chronyc sources
  
- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  
- name: Ensure group "gpkami01" exists
  ansible.builtin.group:
    name: gpkami01
    state: present
   
- name: Create Users Task
  user:
    name: "{{ user_name }}"
    state: present
    
- name: Creamos el directorio /usr/local/{{ entorno }}/{{ user_home_dir }} si no existe
  file:
    path: "/usr/local/{{ entorno }}/{{ user_home_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: u=rwx,g=rwx,o=r
    state: directory

#Pendiente eliminar quiza
- name: Customize .bashrc
  shell:
    cmd: |
    cat << EOF >> .bashrc
    alias k='kubectl'
    if [ -f /etc/bashrc ]; then
        . /etc/bashrc
    fi
    export PS1="🔱⛵ [\e[31m\][\[\e[m\]\[\e[38;5;172m\]\u\[\e[m\]@\[\e[38;5;153m\]\h\[\e[m\] \[\e[38;5;214m\]\W\[\e[m\]\[\e[31m\]]\[\e[m\]\\$ "
    export http_proxy=http://10.200.140.230:80
    export https_proxy=http://10.200.140.230:80
    EOF


- name: Load .bashrc at user login
  shell: source .bashrc && echo "source ~/.bashrc" > .profile
  args:
    executable: /bin/bash
            
- name: Recursively change ownership of a directory
  file:
    path: "{{ user_home_dir }}"
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

- name: Add group to sudoers
  shell: echo "gpkami01 ALL=(ALL) ALL" >> /etc/sudoers
  args:
    executable: /bin/bash
    
- name: Generate /etc/hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts 
    
- name: Disable SWAP because k8s can't work with swap enabled (1/2)
  ansible.builtin.shell: swapoff -a

- name: Disable SWAP in fstab because k8s can't work with swap enabled (2/2)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

- name: Load required modules
  community.general.modprobe:
    name: '{{ item }}'
    state: present
  with_items: '{{ modules }}'
    
- name: Create the .conf file to load the modules at bootup
  ansible.builtin.template:
    src: kernel_modules.conf.j2
    dest: /etc/modules-load.d/k8s_kernel_modules.conf

- name: Modify sysctl entries
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: True
  with_items:
    - {key: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - {key: net.bridge.bridge-nf-call-iptables,  value: 1}
    - {key: net.ipv4.ip_forward,  value: 1}
    
- name: Setup required sysctl params
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - {key: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - {key: net.bridge.bridge-nf-call-iptables,  value: 1}
    - {key: net.ipv4.ip_forward,  value: 1}
    
- name: Add kubernetes repository and proxy
  ansible.builtin.template:
    src: 'kubernetes.repo.j2'
    dest: /etc/yum.repos.d/kubernetes.repo
    
- name: Update system packages
  package:
    name: "*"
    state: latest
  
- name: Disable firewalld service
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
    
- name: Para que se apliquen los cambios
  ansible.builtin.shell: sysctl --system
  
- name: Reinicio de la máquina
  ansible.builtin.shell: reboot
