---

- name: RKE2 agent(worker) y server(master) tareas
  vars:
    caller_role_name: agent
  include_role:
    name: rke2_common
    tasks_from: main

- name: El archivo de configuración ya tiene token de servidor? # comando noqa en lugar de shell
  command: 'grep -i "^token:" /etc/rancher/rke2/config.yaml'
  register: server_token_check
  failed_when: server_token_check.rc >= 2
  changed_when: false

- name: Agregamos token a config.yaml
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars[groups['rke2_servers'][0]].rke2_config_token }}"
    state: present
    insertbefore: BOF
  when:
    - '"token:" not in server_token_check.stdout'

- name: El archivo de configuración ya tiene la URL del servidor? # comando noqa en lugar de shell
  command: 'grep -i "^server:" /etc/rancher/rke2/config.yaml'
  register: server_url_check
  failed_when: server_url_check.rc >= 2
  changed_when: false

- name: Agregamos URL del servidor al archivo de configuración
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ kubernetes_api_server_host }}:9345"
    state: present
    insertbefore: BOF
  when:
    - '"server:" not in server_url_check.stdout'

- name: Iniciamos rke2-agent
  systemd:
    name: rke2-agent.service
    state: started
    enabled: yes
    daemon_reload: yes
