---
- name: CIS MODE
  become: yes
  when: rke2_config.profile | default("") | regex_search('cis-\\d+.\\d+')
  block:

    - name: Creamos grupo etcd
      group:
        name: etcd
        state: present

    - name: Creamos usuario etcd
      user:
        name: etcd
        comment: etcd user
        shell: /bin/nologin
        group: etcd

    - name: Copiamos el archivo systemctl para el kernel hardening para instalaciones de yum
      copy:
        src: /usr/share/rke2/rke2-cis-sysctl.conf
        dest: /etc/sysctl.d/60-rke2-cis.conf
        remote_src: yes
        mode: 0600
      register: sysctl_operation_yum
      when:
        - ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'
        - not rke2_binary_tarball_check.stat.exists

    - name: Copiamos el archivo systemctl para el kernel hardening para instalaciones que no sean yum
      copy:
        src: /usr/local/share/rke2/rke2-cis-sysctl.conf
        dest: /etc/sysctl.d/60-rke2-cis.conf
        remote_src: yes
        mode: 0600
      register: sysctl_operation_tarball
      when: >-
        (ansible_facts['os_family'] != 'RedHat' and
        ansible_facts['os_family'] != 'Rocky') or
        rke2_binary_tarball_check.stat.exists

    - name: Reiniciamos systemd-sysctl
      service:
        state: restarted
        name: systemd-sysctl
      when: sysctl_operation_yum.changed or sysctl_operation_tarball.changed

    - name: Reiniciamos la máquina (esperamos 5 minutos)
      reboot:
        reboot_timeout: 300
      when: sysctl_operation_yum.changed or sysctl_operation_tarball.changed
