---

- name: Habilitamos el puerto 9345
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "9345"
    ctstate: NEW
    jump: ACCEPT
  when: inventory_hostname in groups['rke2_servers']

- name: Habilitamos el puerto 6443
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "6443"
    ctstate: NEW
    jump: ACCEPT
  when: inventory_hostname in groups['rke2_servers']

- name: Habilitamos el puerto udp 8472
  iptables:
    action: insert
    chain: INPUT
    protocol: udp
    destination_port: "8472"
    ctstate: NEW
    jump: ACCEPT

- name: Habilitamos el puerto 10250
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "10250"
    ctstate: NEW
    jump: ACCEPT

- name: Habilitamos el puerto 2379
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "2379"
    ctstate: NEW
    jump: ACCEPT
  when: inventory_hostname in groups['rke2_servers']

- name: Habilitamos el puerto 2380
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "2380"
    ctstate: NEW
    jump: ACCEPT
  when: inventory_hostname in groups['rke2_servers']

- name: Habilitamos el puerto 30000:32767
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "30000:32767"
    ctstate: NEW
    jump: ACCEPT

- name: Habilitamos el puerto 443
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    ctstate: NEW
    jump: ACCEPT

- name: "Habilitamos cluster-cidr forward"
  iptables:
    action: insert
    chain: FORWARD
    source: '{{ rke2_config["cluster-cidr"] | default("10.42.0.0/16") | string }}'
    jump: ACCEPT

- name: "Habilitamos cluster-cidr forward"
  iptables:
    action: insert
    chain: FORWARD
    destination: '{{ rke2_config["cluster-cidr"] | default("10.42.0.0/16") | string }}'
    jump: ACCEPT

- name: "Habilitamos cluster-cidr input"
  iptables:
    action: insert
    chain: INPUT
    source: '{{ rke2_config["cluster-cidr"] | default("10.42.0.0/16") | string }}'
    jump: ACCEPT

- name: "Habilitamos cluster-cidr input"
  iptables:
    action: insert
    chain: INPUT
    destination: '{{ rke2_config["cluster-cidr"] | default("10.42.0.0/16") | string }}'
    jump: ACCEPT

- name: Guardamos iptables
  shell: "iptables-save > /etc/sysconfig/iptables"
  become: true
  changed_when: false
  when: ansible_facts['os_family'] == 'RedHat'

- name: Instalamos iptables-persistent
  apt:
    name: iptables-persistent
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Guardamos iptables
  shell: "iptables-save > /etc/iptables/rules.v4"
  become: true
  changed_when: false
  when: ansible_facts['os_family'] == 'Debian'
