---
- hosts: localhost
  become: true
  become_method: sudo
  roles:
    - semaphore
    
#usando el inventario
- hosts: setup
  become: true
  become_method: sudo
  roles:
    - common
    
#usando el inventario hosts.ini
- hosts: rke2_cluster
  become: true
  become_method: sudo
  roles:
    - common
  
- hosts: registry
  become: true
  become_method: sudo
  roles:
    - registry

- hosts: localhost
  become: true
  become_method: sudo
  roles:
    - registry

- name: Server play
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_server
  serial: 1

- name: Agent play
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_agent
  serial: 2





#TODO REVISAR
- hosts: bastion
  become: true
  become_method: sudo
  roles:
    - bastion
    
- hosts: balanceadores
  become: true
  become_method: sudo
  roles:
    - balanceador
