---
- name: Listar imagenes y guardar el valor
  shell: |
    kubeadm config images list --kubernetes-version {{ kubernetes_version}}
  register: result_images
  when: inventory_hostname == groups['masters'][0]

- name: saving the file names
  set_fact:
    result_images_list: "{{ result_images_list|default([]) + [ item|trim ] }}"
  with_items: "{{ (result_images.stdout).split('\n') }}"
  when: inventory_hostname == groups['masters'][0]

- name: Hacemos login con el Registry
  shell: nerdctl login {{ registry_domain }}:{{ registry_port }} -u "{{ registry_user }}" -p "{{ registry_pass }}"
  when: inventory_hostname == groups['masters'][0]
  
- name: Nos bajamos las imagenes
  shell: |
     nerdctl pull {{ registry_domain }}:{{ registry_port }}/{{ item }}
  with_items: "{{  result_images_list }}"
  when: inventory_hostname == groups['masters'][0]

- name: Hacemos una tag para cada imagen
  shell: |
    nerdctl tag {{ registry_domain }}:{{ registry_port }}/{{ item }} {{ registry_domain }}:{{ registry_port }}/transformacion/{{  item.split('/') | last  }} 
  with_items: "{{  result_images_list  }}"
  when: inventory_hostname == groups['masters'][0]

- name: Subimos las imagenes la registry
  shell: |
    nerdctl push {{ registry_domain }}:{{ registry_port }}/transformacion/{{  item.split('/') | last  }}
  with_items: "{{  result_images_list  }}"
  when: inventory_hostname == groups['masters'][0]