
---
# tasks file for Kubernetes nodes

- name: Instala containerd y las dependencias (común todos los nodos)
  import_tasks: install-containerd.yaml
  tags: containerd-install

- name: Instala kubeadm, kubelet y kubectl (común todos los nodos)
  import_tasks: install-kube.yaml
  tags: kube-install

- name: Configurando imagenes ( solo en un master )
  import_tasks: config-images.yaml
  tags: config-images
  
#- name: Inicializa cluster de kube (master 1)
#  import_tasks: create-cluster.yaml
#  tags: create-cluster

#- name: Añade otros master y worker al cluster
#  import_tasks: join-nodes.yaml
#  tags: join-nodes

#- name: Instalación y configuración de Trident
#  import_tasks: install-trident.yaml
#  tags: trident
