---

- name: Habilita el puerto 10250 TCP
  firewalld:
    port: 10250/tcp
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Habilita el rango de puertos 30000-32767 TCP
  firewalld:
    port: 30000-32767/tcp
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Set masquarade for public zone
  firewalld:
    zone: public
    masquerade: yes
    immediate: yes
    permanent: yes
    state: enabled

- name: Check if kubelet.conf exists
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

#- name: Join nodes to the cluster
#  shell: kubeadm join {{ groups['bal_vip'][0] }}:6443 --token {{ hostvars[groups['masters'][0]]['kubeadm_token'] }} --discovery-token-ca-cert-hash {{ hostvars[groups['masters'][0]]['token_ca'] }}  
#  become: yes
#  when: not kubelet_conf.stat.exists

