---

- name: Server play
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_server
  serial: 3

- name: Agent play
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_agent
  serial: 3
