---

- name: Reiniciamos systemd-sysctl
  service:
    state: restarted
    name: systemd-sysctl

- name: Reiniciamos rke2-server
  service:
    state: restarted
    name: rke2-server

- name: Reiniciamos rke2-agent
  service:
    state: restarted
    name: rke2-agent
